version: '3.8'
services:
  trade_me_db:
    image: postgres:15-alpine
    container_name: trade_me_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecretPass123
      POSTGRES_DB: myapp_a
      TZ: Asia/Kuala_Lumpur
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - trade_me_net

  trade_me_app:
    build: .
    container_name: trade_me_app
    restart: always
    depends_on:
      - trade_me_db
    environment:
      - PORT=3000
      - TOKEN_KEY=SecretKeyForClientA
      - TZ=Asia/Kuala_Lumpur
      - DB=postgresql://postgres:MySecretPass123@trade_me_db:5432/myapp_a
    networks:
      - trade_me_net
      - caddy_net
    volumes:
      - ./public/lang:/app/public/lang

networks:
  trade_me_net:
  caddy_net:
    external: true
