version: '3.8'

services:
  etsy_db:
    image: postgres:15-alpine
    container_name: etsy_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecretPass123
      POSTGRES_DB: myapp_b
      TZ: Asia/Kuala_Lumpur
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5434:5432"
    networks:
      - etsy_net

  # Etsy 应用
  etsy_app:
    build: .
    container_name: etsy_app
    restart: always
    depends_on:
      - etsy_db
    environment:
      - PORT=3000
      - TOKEN_KEY=SecretKeyForClientA
      - TZ=Asia/Kuala_Lumpur
      - DB=postgresql://postgres:MySecretPass123@etsy_db:5432/myapp_b
    networks:
      - etsy_net
      - caddy_net
    volumes:
      - ./public/lang:/app/public/lang

networks:
  etsy_net: # 项目内部私有网络
  caddy_net: # Caddy 的公共桥梁网络
    external: true